services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  node:
    image: node:20
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www
    command: sh -c "npm install && npm run dev"

volumes:
  pgdata: